MiageMonitor.Web/Models/ErrorViewModel.cs
using System;

namespace MiageMonitor.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MiageMonitor.Web/Controllers/EtudiantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using MiageMonitor.Data.Contexts;
using MiageMonitor.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MiageMonitor.Web.Controllers
{
    public class EtudiantsController : Controller
    {
        private readonly MiageContext _miageContext;
        private readonly HttpClient _httpClient;

        public EtudiantsController(MiageContext miageContext)
        {
            _miageContext = miageContext;
            _httpClient = new HttpClient();
        }


        [HttpGet]
        public IEnumerable<Etudiant> GetEtudiantsFromEntityFramework()
        {
            IEnumerable<Etudiant> etudiants = null;
            try
            {
                etudiants = _miageContext.Etudiants;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            return etudiants;
        }

        [HttpGet]
        public IEnumerable<Etudiant> GetEtudiantsFromLocalAPI()
        {
            IEnumerable<Etudiant> etudiants = null;
            try
            {
                string json = _httpClient.GetStringAsync("https://localhost:5003/api/Etudiants").Result;
                etudiants = JsonConvert.DeserializeObject<IEnumerable<Etudiant>>(json);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            return etudiants;
        }

        [HttpPost]
        public IActionResult AddEtudiantFromLocalAPI(Etudiant etudiant)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            var result = _httpClient.PostAsJsonAsync("https://localhost:5003/api/Etudiants", etudiant).Result;

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult AddEtudiantFromLocalAPI()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEtudiantFromEntityFramework(Etudiant etudiant)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _miageContext.Etudiants.Add(etudiant);
            _miageContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult AddEtudiantFromEntityFramework()
        {
            return View();
        }

        public IActionResult Index()
        {
            ViewBag.EtudiantsFromEF = GetEtudiantsFromEntityFramework();
            ViewBag.EtudiantsFromLocalAPI = GetEtudiantsFromLocalAPI();

            return View();
        }
    }
}

MiageMonitor.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MiageMonitor.Web.Models;

namespace MiageMonitor.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MiageMonitor.Web/Views/Etudiants/AddEtudiantFromEntityFramework.cshtml
@model MiageMonitor.Data.Models.Etudiant
@{
    ViewData["Title"] = "Ajouter un étudiant";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="AddEtudiantFromEntityFramework" asp-controller="Etudiants">
    <div class="form-group row">
        <label asp-for="Nom" class="col-form-label col-sm-2"></label>
        <input asp-for="Nom" type="text" class="form-control col-sm-6" />
        <span asp-validation-for="Nom" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Prenom" class="col-form-label col-sm-2"></label>
        <input asp-for="Prenom" type="text" class="form-control col-sm-6" />
        <span asp-validation-for="Prenom" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="DateNaissance" class="col-form-label col-sm-2"></label>
        <input asp-for="DateNaissance" type="date" class="form-control col-sm-6" />
        <span asp-validation-for="DateNaissance" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="NumeroEtudiant" class="col-form-label col-sm-2"></label>
        <input asp-for="NumeroEtudiant" type="number" class="form-control col-sm-6" />
        <span asp-validation-for="NumeroEtudiant" class="text-danger"></span>
    </div>
    
    <input type="submit" class="btn btn-primary" value="Ajouter l'étudiant" />
</form>

MiageMonitor.Web/Views/Etudiants/AddEtudiantFromLocalAPI.cshtml
@model MiageMonitor.Data.Models.Etudiant
@{
    ViewData["Title"] = "Ajouter un étudiant";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="AddEtudiantFromLocalAPI" asp-controller="Etudiants">
    <div class="form-group row">
        <label asp-for="Nom" class="col-form-label col-sm-2"></label>
        <input asp-for="Nom" type="text" class="form-control col-sm-6" />
        <span asp-validation-for="Nom" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Prenom" class="col-form-label col-sm-2"></label>
        <input asp-for="Prenom" type="text" class="form-control col-sm-6" />
        <span asp-validation-for="Prenom" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="DateNaissance" class="col-form-label col-sm-2"></label>
        <input asp-for="DateNaissance" type="date" class="form-control col-sm-6" />
        <span asp-validation-for="DateNaissance" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="NumeroEtudiant" class="col-form-label col-sm-2"></label>
        <input asp-for="NumeroEtudiant" type="number" class="form-control col-sm-6" />
        <span asp-validation-for="NumeroEtudiant" class="text-danger"></span>
    </div>

    <input type="submit" class="btn btn-primary" value="Ajouter l'étudiant" />
</form>

MiageMonitor.Web/Views/Etudiants/Index.cshtml
@using MiageMonitor.Data.Models;
@{
    IEnumerable<Etudiant> etudiantsFromEF = (IEnumerable<Etudiant>)ViewBag.EtudiantsFromEF;
    IEnumerable<Etudiant> etudiantsFromLocalAPI = (IEnumerable<Etudiant>)ViewBag.EtudiantsFromLocalAPI;
    ViewData["Title"] = "Liste des étudiants";
}

<h1>@ViewData["Title"]</h1>

<h2>Etudiants depuis EF Core</h2>
@if (etudiantsFromEF is null)
{
    <p class="text-danger">Une erreur est survenue lors de l'appel à Entity Framework.</p>
}
else
{
    <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Date de naissance</th>
            <th>Numéro étudiant</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var etudiant in etudiantsFromEF)
        {
            <tr>
                <td>@etudiant.Nom</td>
                <td>@etudiant.Prenom</td>
                <td>@etudiant.DateNaissance</td>
                <td>@etudiant.NumeroEtudiant</td>
            </tr>
        }
        </tbody>
    </table>
}

<h2>Etudiants depuis l'API locale</h2>
@if (etudiantsFromLocalAPI is null)
{
    <p class="text-danger">Une erreur est survenue lors de l'appel à l'API.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date de naissance</th>
                <th>Numéro étudiant</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var etudiant in etudiantsFromLocalAPI)
            {
                <tr>
                    <td>@etudiant.Nom</td>
                    <td>@etudiant.Prenom</td>
                    <td>@etudiant.DateNaissance</td>
                    <td>@etudiant.NumeroEtudiant</td>
                </tr>
            }
        </tbody>
    </table>
}

MiageMonitor.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Accueil";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>

MiageMonitor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiageMonitor.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark text-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MiageMonitor.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Etudiants" asp-action="Index">Etudiants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Etudiants" asp-action="AddEtudiantFromEntityFramework">Ajouter un étudiant (EF)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Etudiants" asp-action="AddEtudiantFromLocalAPI">Ajouter un étudiant (API locale)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MiageMonitor.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>